---
- hosts: vagrants
  become: true
  user: vagrant
  tasks:
    - name: install package-query (a yaourt dependency)
      include: aur/pkg.yml pkg_name=package-query

    - name: install yaourt
      include: aur/pkg.yml pkg_name=yaourt
